### ISSUE TITLE
【新功能】支持手机号登录，支持二维码扫码登录

### ISSUE THREAD

**Issue by meimosor** [NotFound403/id-server#17]
支持手机号登录，支持二维码扫码登录

**Comment by NotFound403** [comment]
通过 [https://gitee.com/felord/spring-security-login-extension](https://gitee.com/felord/spring-security-login-extension) 验证码登录集成包进行扩展，这里不再集成。

**Comment by NotFound403** [comment]
考虑了一下，接入也没有什么成本，在#24中增加了接入验证码
