### ISSUE TITLE
请问这种客户端模式还能把登录页面拆出来吗

### ISSUE THREAD

**Issue by icuxika** [NotFound403/id-server#23]
我想将登录页面在Vue中实现，但是客户端模式下，登录页是直接重定向到授权服务器去了，这样似乎没法做到使用axios发送请求来进行登录，vuejs+springcloud的组合适合客户端模式吗

**Comment by meimosor** [comment]
可以扩展下password模式，前台把client信息base64后加上用户名密码登录

**Comment by NotFound403** [comment]
> 可以扩展下password模式，前台把client信息base64后加上用户名密码登录

和协议不符，如果有需要自行扩展，这个问题到此为止
