### ISSUE TITLE
【Update】依赖更新，升级Authorization Server版本

### ISSUE THREAD

**Issue by meimosor** [NotFound403/id-server#26]
Hello, Spring Authorization Server已发布0.3.0版本，是否考虑下升级到最新

**Comment by NotFound403** [comment]
新的版本已经升级到 [sas0d3分支](https://github.com/NotFound403/id-server/tree/sas0d3)，升级说明：

> **版本升级**
> - 升级 Spring Authorization Server 版本到0.3.0
> - 升级 Spring Boot 版本到2.7.0
> 
> BREAKING CHANGE: 最低的Java运行时版本为11

但是并不会立刻合并到 master。
