### ISSUE TITLE
关于访问其他请求返回500错误的问题

### ISSUE THREAD

**Issue by ebdmn** [NotFound403/id-server#28]
样例客户端在samples文件夹下，直接启动，浏览器配置文件下的http://127.0.0.1:8082/foo/bar，进入登录页，输入用户名user和密码user即可 这一步是没问题的
但是如果请求其他请求，例如 http://127.0.0.1:8082/ 进入登录界面，输入用户名密码 就会跳转到500错误页面

**Comment by NotFound403** [comment]
@ebdmn  请详细描述你的流程

**Comment by ebdmn** [comment]
这个重定向uri 其实是有逻辑处理的是吧？不仅仅是简单的一个重定向，而是授权成功的一个逻辑处理

**Comment by ebdmn** [comment]
> @ebdmn `http://127.0.0.1:8082/` 并不是合法的重定向uri ，参考项目中的`dml.sql`。非法的重定向uri参与的授权是不被接受的，不知道这样说你明白了没有？

这个重定向uri 其实是有逻辑处理的是吧？不仅仅是简单的一个重定向，而是授权成功的一个逻辑处理

**Comment by NotFound403** [comment]
> > @ebdmn `http://127.0.0.1:8082/` 并不是合法的重定向uri ，参考项目中的`dml.sql`。非法的重定向uri参与的授权是不被接受的，不知道这样说你明白了没有？
> 
> 这个重定向uri 其实是有逻辑处理的是吧？不仅仅是简单的一个重定向，而是授权成功的一个逻辑处理

localhost 不是合法的oauth2 host和逻辑无关，相关说明在rfc6749，这个问题没有继续深究的价值
