### ISSUE TITLE
请问针对前后端分离使用ajax请求的情况如何优雅的做到跳转登录

### ISSUE THREAD

**Issue by limng06** [NotFound403/id-server#29]
请问针对前后端分离使用ajax请求的情况如何优雅的做到跳转登录
前后端分离部署，后端接口无状态，如何设计授权码流程

**Comment by NotFound403** [comment]
问题过于宏大，请详细描述场景 @limng06

**Comment by limng06** [comment]
> 

我看了下PKCE的流程 应该比较符合这个情况，前端就当作一个SPA应用，是否可行，准备这么干了

**Comment by shanzhaozhen** [comment]
> > @NotFound403
> 
> 我看了下PKCE的流程 应该比较符合这个情况，前端就当作一个SPA应用，是否可行，准备这么干了

感谢你的启发
