### ISSUE TITLE
问一下客户端的private_key_jwt怎么配置呢？

### ISSUE THREAD

**Issue by Kevin517** [NotFound403/id-server#31]
改了client-authentication-method总是报失败

**Comment by NotFound403** [comment]
@Kevin517  具体一些    如果使用其它 客户端认证方式  可以参考提供的demo 进行修改

**Comment by Kevin517** [comment]
> @Kevin517 具体一些 如果使用其它 客户端认证方式 可以参考提供的demo 进行修改

Client Demo里能有一个jwkSetUrl的业务处理、适配RsaKey等private_key_jwt方式认证的模板吗？感谢

**Comment by NotFound403** [comment]
> private_key_jwt

客户端要对授权服务器提供一个jwk端点用来协助授权服务器对客户端进行防伪认证，具体的流程和原理参见[OAuth2客户端认证方式private_key_jwt的Java实现](https://felord.blog.csdn.net/article/details/123982598)。当然你也可以随时在该issue下发起提问。
