### ISSUE TITLE
请问使用py语言开发的项目使用id-server，需要额外做哪些工作

### ISSUE THREAD

**Issue by luyuanx2** [NotFound403/id-server#32]

**Comment by luyuanx2** [comment]
> 遵循 oauth2协议即可，python项目作为客户端 注册到id server上 然后按照标准oauth2协议发起授权 需要认证就按找oidc协议进行客户端配置

登录成功，带着token访问py项目，token校验这块是不是要自己写，我理解的是如果用了spring-security，框架会自动做toekn校验

**Comment by NotFound403** [comment]
参考jose规范自行实现
