### ISSUE TITLE
请问怎么配置前后端分离的认证？

### ISSUE THREAD

**Issue by bulldriver** [NotFound403/id-server#37]
直接使用POST /login 传用户名密码进行登录认证，然后取得access token ,而不是使用浏览器的登录页？

**Comment by shanzhaozhen** [comment]
> 直接使用POST /login 传用户名密码进行登录认证，然后取得access token ,而不是使用浏览器的登录页？

首先你说的这点是密码模式的认证方式，不适用与oauth2.1，或者你可以自己做增强让其支持密码模式，可以看我下面所说的demo的password分支

此外
前后端分离我已经找到一个最佳的方式实现了，主要开启客户端信息的 `clientAuthenticationMethod(ClientAuthenticationMethod.NONE)` 及 `clientSettings` 设置需要设置为 `requireProofKey(true)`，前端应用可以加入 `oidc-client-ts` 依赖，或者按照oauth2的认证流程自己编写代码逻辑。
我实现的方式主要是OIDC + PKCE，具体实例是通过 sas 的 issues 的一个大佬中学习的 [issues地址](https://github.com/spring-projects/spring-authorization-server/issues/539)
也可以通过我最近弄的[demo尝试](https://github.com/shanzhaozhen/best-cloud)，我里面用到的登陆页是按照react项目打包再嵌入到后端服务器使用的，习惯了写前端的伙伴可以使用这种方式整合到java后端，毕竟现在偷懒不写样式太难了，很多组件库都不支持CDN了。
在我学习这个oauth认证过程，感觉大家跟我一样主要卡在的位置是不理解前端一个登陆页，认证服务器一个登陆页应该怎么处理这个认证过程，如果密码模式就直接一个post请求过去就好了。但是用授权码模式的话要抛开这个概念，直接把前端的登录页干掉，没进行认证跳转到欢迎页就好，点击欢迎页的登录再跳转到认证服务器的登录页即可。这个过程你可以看看腾讯的应用，目前都已经看不见登陆页，基本都是oauth授权页是吧。各位不要被企业应用的包袱拖累了。
至于原生APP怎么实现呢，因为可能没办法优雅的嵌入完成，虽然可以弹出一个浏览器窗口进行认证也不是不行，之后再研究怎么实现比较好。
@bulldriver 
@limng06 
@MrQiaoLei
