### ISSUE TITLE
id-server怎么结合现已有的权限呢？

### ISSUE THREAD

**Issue by ttxs0109** [NotFound403/id-server#38]
现在的项目已经有权限管理(基于RBAC), 需要对外开放一些api给第三方。id-server怎么结合现已有的权限呢？

id-server 有张oauth2_scope表 -> scope 字段是不是可以对接现有系统的权限角色,然后第三方就拥有访问权限了

**Comment by NotFound403** [comment]
id server 只负责发token       你只需要指定你资源服务器接口对应的scope
