### ISSUE TITLE
[invalid_user_info_response] An error occurred while attempting to retrieve the UserInfo Resource: 403 : "{"error":"insufficient_scope"}"

### ISSUE THREAD

**Issue by blueskyzh2020** [NotFound403/id-server#41]
认证成功后，后台log也能看出从oidc方法中取得用户信息，但重定向回client，总是又回到login page，上面显示“[invalid_user_info_response] An error occurred while attempting to retrieve the UserInfo Resource: 403 : "{"error":"insufficient_scope"}"

始终没找到原因，麻烦帮忙指导一下？多下。

**Comment by NotFound403** [comment]
提供的信息不够，希望有可复现的步骤

**Comment by blueskyzh2020** [comment]
这个问题是在您框架上添加自定义password模式出现的问题。现在很多前后端分离模式都需要这种认证模式，可惜被新oauth2.1删除了。如果您框架有添加好的password模式的框架最好。

**Comment by NotFound403** [comment]
> 这个问题是在您框架上添加自定义password模式出现的问题。现在很多前后端分离模式都需要这种认证模式，可惜被新oauth2.1删除了。如果您框架有添加好的password模式的框架最好。

密码模式不会得到支持，Oauth2.1移除它是合理的
